apiVersion: v1
kind: Service
metadata: 
   name: backend-service
spec: 
   selector:
      app: beans-new
      tier: backend
   ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
   type: LoadBalancer 